version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: youtubedb
    ports:
      - '5432:5432'
  web:
    build: .
    env_file: .env
    ports:
      - '8000:8000'
    depends_on:
      - db
